/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled 2"
  https://create.arduino.cc/cloud/things/447e0923-1466-40bb-ae85-6567cc4fb4f2 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  bool led;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

// Define the LED pin

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
  
  pinMode(LED_BUILTIN,OUTPUT);
  
}

// Define dot and dash durations (adjust as needed)
const int dotDuration = 200;
const int dashDuration = dotDuration * 3;
const int interDotDashDuration = dotDuration;
const int letterGapDuration = dotDuration * 3;
const int wordGapDuration = dotDuration * 7;
  
int BUTTON_PIN = 3;

const char *morseCode[] = {".-", "-...", "-.-.", "-..", ".", "..-.", "--.", "....", "..", ".---", "-.-", ".-..", "--", "-.", "---", ".--.", "--.-", ".-.", "...", "-", "..-", "...-", ".--", "-..-", "-.--", "--.."};

void dot() {
  digitalWrite(LED_BUILTIN, HIGH);
  delay(dotDuration);
  digitalWrite(LED_BUILTIN, LOW);
  delay(interDotDashDuration);
}

void dash() {
  digitalWrite(LED_BUILTIN, HIGH);
  delay(dashDuration);
  digitalWrite(LED_BUILTIN, LOW);
  delay(interDotDashDuration);
}

void generateMorseCode(char c) {
  int index = c - 'A';
  if (index >= 0 && index < 26) {
    for (int i = 0; morseCode[index][i] != '\0'; i++) {
      if (morseCode[index][i] == '.') {
        dot();
      } else if (morseCode[index][i] == '-') {
        dash();
      }
    }
    delay(letterGapDuration);
  }
}


void displayCode()
{
  String message = "TANMAY"; 

  for (int i = 0; i < message.length(); i++) {
    if(led == HIGH || digitalRead(BUTTON_PIN) == HIGH)
    {
      displayCode();
    };
    char c = toupper(message.charAt(i));
    if (c == ' ') {
      delay(wordGapDuration);
    } else {
      generateMorseCode(c);
    }
  }

  
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  while (led == HIGH || digitalRead(BUTTON_PIN) == HIGH){
    displayCode();
  }
  
}


/*
  Since Led is READ_WRITE variable, onLedChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLedChange()  
{
  // Add your code here to act upon Led change
}


